### ISSUE TITLE
extract_image_features.bin

### ISSUE THREAD

**Issue by woshigcy** [zhengshou/scnn#28]
I1130 15:35:33.930305 25336 net.cpp:322] Copying source layer fc7-1-convdeconv
I1130 15:35:34.657407 25336 net.cpp:322] Copying source layer relu7
I1130 15:35:34.657439 25336 net.cpp:322] Copying source layer drop7
I1130 15:35:34.657449 25336 net.cpp:322] Copying source layer predict
I1130 15:35:34.661358 25336 net.cpp:322] Copying source layer loss
E1130 15:35:34.663674 25336 extract_image_features.cpp:72] Extracting features for 1 batches
I1130 15:35:34.852460 25502 video_segmentation_data_layer.cpp:204] Restarting data prefetching from start.
E1130 15:35:35.188673 25336 extract_image_features.cpp:108] Extracted features of 4 images.
E1130 15:35:35.188693 25336 extract_image_features.cpp:112] Successfully extracted 4 features!
*** Error in `../CDC/build/tools/extract_image_features.bin': double free or corruption (out): 0x00000000028e12c0 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f0ab5a437e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f0ab5a4c37a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f0ab5a5053c]
/usr/local/lib/libprotobuf.so.9(_ZN6google8protobuf8internal28DestroyDefaultRepeatedFieldsEv+0x1f)[0x7f0aba6ceb5f]
/usr/local/lib/libprotobuf.so.9(_ZN6google8protobuf23ShutdownProtobufLibraryEv+0x8b)[0x7f0aba6cdf4b]
/usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3(+0x233b9)[0x7f0aa08103b9]
/lib64/ld-linux-x86-64.so.2(+0x10de7)[0x7f0ac1a58de7]
/lib/x86_64-linux-gnu/libc.so.6(+0x39ff8)[0x7f0ab5a05ff8]
/lib/x86_64-linux-gnu/libc.so.6(+0x3a045)[0x7f0ab5a06045]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf7)[0x7f0ab59ec837]
../CDC/build/tools/extract_image_features.bin[0x40d399]

Anyone have a suggestion?

**Comment by Multihuntr** [comment]
For starters, that is referring to the `extract_image_features.bin` in a CDC installation, rather than the C3Dv1.0 or C3Dv1.1 installations that this repo uses.

But you may get the same error if you point it to the right `extract_image_features.bin`. With regards to solving the error; googling "DestroyDefaultRepeatedFields" (from the error message) suggests that somehow there are two calls to "ShutdownProtobufLibrary", perhaps from [both protobuf and protobuf-lite being used](https://github.com/google/protobuf/issues/44)

**Comment by zhengshou** [comment]
Thanks for the clarification!

**Comment by 953585130** [comment]
Hello, I encountered the same problem when extracting my own video features. Have you solved this problem? If you have solved it, please give me some help, thank you very much.
