### ISSUE TITLE
metric_of_action_localization

### ISSUE THREAD

**Issue by liu666666** [zhengshou/scnn#4]
Hi,Thanks for your sharing!
I am confused about the metric of action localization, I have 2 questions:
1, every video should be predicted with the start time and end time , also the video label, I want to know that the label influence the mAP of the action localization? If influence ,how?  i see that IoU greater than 0.5
is ok.
2. In the test videos ,some video do not contain the action, what should the predicted result be? I think you did not predict these videos which do not contain the action  according to your paper.

Thanks for your kindly help and nice job!

**Comment by zhengshou** [comment]
Hi, we follow standard metrics for evaluation.

1. Yes. definitely influence. only detection with correct label prediction will be counted as true positive. Please read the experimental section in our paper carefully and then play around with the THUMOS official eval code in order to better and fully understand the metrics. You may need search online to learn how to compute mAP if you are not familiar.
2. ideally won't have predictions for these videos because these videos should be predicted as background.
